import { Dumbbell, GlassWater, BookOpen, Coffee, Briefcase, Heart, Star, Zap, } from 'lucide-svelte';
// Types
export type Category = 'Wajib' | 'Sunnah' | 'Mubah';


export const categories: { label: Category; color: string; description: string; labelKey: string; descKey: string }[] = [
	{ label: 'Wajib', color: 'primary', description: 'Ibadah wajib yang harus ditunaikan.', labelKey: 'category_wajib', descKey: 'category_wajib_desc' },
	{ label: 'Sunnah', color: 'secondary', description: 'Amalan sunnah untuk pahala tambahan.', labelKey: 'category_sunnah', descKey: 'category_sunnah_desc' },
	{ label: 'Mubah', color: 'accent', description: 'Aktivitas harian yang bermanfaat.', labelKey: 'category_mubah', descKey: 'category_mubah_desc' }
];

export const icons = [
	{ component: Dumbbell, label: 'Olahraga', labelKey: 'icon_sports' },
	{ component: BookOpen, label: 'Membaca', labelKey: 'icon_reading' },
	{ component: GlassWater, label: 'Minum', labelKey: 'icon_drinking' },
	{ component: Coffee, label: 'Santai', labelKey: 'icon_relax' },
	{ component: Briefcase, label: 'Bekerja', labelKey: 'icon_work' },
	{ component: Heart, label: 'Kesehatan', labelKey: 'icon_health' },
	{ component: Star, label: 'Target', labelKey: 'icon_target' },
	{ component: Zap, label: 'Energi', labelKey: 'icon_energy' }
];



export const surahs = [
	'Al-Fatihah',
	'Al-Baqarah',
	"Ali 'Imran",
	'An-Nisa',
	"Al-Ma'idah",
	"Al-An'am",
	"Al-A'raf",
	'Al-Anfal',
	'At-Tawbah',
	'Yunus',
	'Hud',
	'Yusuf',
	"Ar-Ra'd",
	'Ibrahim',
	'Al-Hijr',
	'An-Nahl',
	'Al-Isra',
	'Al-Kahf',
	'Maryam',
	'Ta-Ha',
	'Al-Anbiya',
	'Al-Hajj',
	"Al-Mu'minun",
	'An-Nur',
	'Al-Furqan',
	"Ash-Shu'ara",
	'An-Naml',
	'Al-Qasas',
	'Al-Ankabut',
	'Ar-Rum',
	'Luqman',
	'As-Sajdah',
	'Al-Ahzab',
	'Saba',
	'Fatir',
	'Ya-Sin',
	'As-Saffat',
	'Sad',
	'Az-Zumar',
	'Ghafir',
	'Fussilat',
	'Ash-Shura',
	'Az-Zukhruf',
	'Ad-Dukhan',
	'Al-Jathiyah',
	'Al-Ahqaf',
	'Muhammad',
	'Al-Fath',
	'Al-Hujurat',
	'Qaf',
	'Adh-Dhariyat',
	'At-Tur',
	'An-Najm',
	'Al-Qamar',
	'Ar-Rahman',
	"Al-Waqi'ah",
	'Al-Hadid',
	'Al-Mujadila',
	'Al-Hashr',
	'Al-Mumtahanah',
	'As-Saff',
	"Al-Jumu'ah",
	'Al-Munafiqun',
	'At-Taghabun',
	'At-Talaq',
	'At-Tahrim',
	'Al-Mulk',
	'Al-Qalam',
	'Al-Haqqah',
	"Al-Ma'arij",
	'Nuh',
	'Al-Jinn',
	'Al-Muzzammil',
	'Al-Muddathir',
	'Al-Qiyamah',
	'Al-Insan',
	'Al-Mursalat',
	'An-Naba',
	"An-Nazi'at",
	'Abasa',
	'At-Takwir',
	'Al-Infitar',
	'Al-Mutaffifin',
	'Al-Inshiqaq',
	'Al-Buruj',
	'At-Tariq',
	"Al-A'la",
	'Al-Ghashiyah',
	'Al-Fajr',
	'Al-Balad',
	'Ash-Shams',
	'Al-Layl',
	'Ad-Duha',
	'Ash-Sharh',
	'At-Tin',
	'Al-Alaq',
	'Al-Qadr',
	'Al-Bayyinah',
	'Az-Zalzalah',
	'Al-Adiyat',
	"Al-Qari'ah",
	'At-Takathur',
	'Al-Asr',
	'Al-Humazah',
	'Al-Fil',
	'Quraysh',
	"Al-Ma'un",
	'Al-Kawthar',
	'Al-Kafirun',
	'An-Nasr',
	'Al-Masad',
	'Al-Ikhlas',
	'Al-Falaq',
	'An-Nas'
];

export type UserPreferences = {
	notificationSettings?: {
		prayers: Record<string, boolean>;
		habits: boolean;
		sound: string;
	};
};
